@startuml

skinparam linetype ortho

Entity Клиент {
  *Название
  *ИНН
  *КПП
  *ОГРН
  *Юридический адрес
  *Имя директора
  *Годовой оборот
}

Entity Представитель_клиента {
  *Имя
  *Фамилия
  *Телефон
  *Email
}

Entity Тариф {
  *Название
  *Комиссия
}

Entity Индивидуальный_Тариф {
  *Доп. условия
  *Скидка
}

Enum Статус_клиента{
  Новый
  Зарегистрирован
  Активирован
  Удален
}

Entity Обьявление {
  *Описание
  *Контакты
  *Стоимость
}

Enum Статус_обьявления {
  Доступно
  Удалено
}


Клиент *--"1,*" Представитель_клиента
Клиент "0,*" --> "0,1" Тариф
Клиент "*" --> "1" Статус_клиента
Клиент "1"*--"0,*" Обьявление

Тариф ^-- Индивидуальный_Тариф
Обьявление "*" --> "1" Статус_обьявления


@enduml